### ISSUE TITLE
Bad renders included in PUG: Animals?

### ISSUE THREAD

**Issue by ThaddaeusWiedemer** [facebookresearch/PUG#3]
Thanks for the great work and publishing this dataset!

I was playing around with PUG: Animals and noticed that some images looked weird and seemed to be rendered incorrectly. E.g., in the below image, as I'm traversing the `world_name` factor (first row), some scenes seem to have incorrect lighting (e.g., `Desert`, `TrainStation`, `SpaceHangar`), clipped objects (e.g., `EuropeanStreet`, `Bridge`) or no background beyond the default skybox (e.g., `SciFiGarage`, `BoxingRing`).

![pug_animals__factors](https://github.com/facebookresearch/PUG/assets/30976585/24f5ca34-0c31-4261-88e6-ba93119c57ad)

Going through different factor combinations for `Goldfish` in the `SciFiGarage` background also shows some bad renders for the different textures, but not for all scales or camera angles:

![pug_animals__factors_2](https://github.com/facebookresearch/PUG/assets/30976585/8fa1a5a8-bef4-4e23-8f40-a4259871c9e9)

This does not seem to be a general problem for all classes, e.g., `Caribou` seems to be rendered correctly for all backgrounds:

![pug_animals__factors_3](https://github.com/facebookresearch/PUG/assets/30976585/7e43956e-9f40-4bbb-8478-da03aee58f43)

Could you please look into this and

1. confirm this issue.
2. analyze the extent of the issue (is it only `Goldfish` or also other characters?)
3. confirm whether this only affects the public dataset or also the dataset used for the experiments in the paper

Here's the code to reproduce my figures:

```python
import torch
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image

PUG_ANIMAL_PATH = ""

class UnrealDataset(torch.utils.data.Dataset):
    def __init__(self, csv_path, images_folder, transform = None):
        self.df = pd.read_csv(csv_path)
        self.df.astype(str)
        self.images_folder = images_folder
        self.transform = transform

    def __len__(self):
        return len(self.df)
    
    def __getDataAlongFactor__(self, factor: str):
        values = self.df[factor].unique().tolist()
        key_value_pairs = {"world_name": "SciFiGarage", "character_name": "Caribou", "character_scale": 0.7, "character_texture": "Default", "camera_yaw": 0}
        
        imgs = []
        for value in values:
            key_value_pairs[factor] = value
            queries = [f"{k} == {v}" if k in ["character_scale", "camera_yaw"] else f"{k} == '{v}'" for k, v in key_value_pairs.items()]
            query_str = " & ".join(queries)
            entry = dataset.df.query(query_str)
            path = os.path.join(self.images_folder, key_value_pairs["character_name"], entry["filename"].iloc[0])
            img = Image.open(path)
            if self.transform is not None:
                img = self.transform(img)
            imgs.append(img)
        
        return imgs, values

dataset = UnrealDataset(csv_path=PUG_ANIMAL_PATH+"labels_pug_animal.csv", images_folder=PUG_ANIMAL_PATH)


factors = ["world_name", "character_name", "character_scale", "character_texture", "camera_yaw"]

fig, axs = plt.subplots(len(factors), 70, figsize=(70*4, len(factors)*4))

for row, f in enumerate(factors):
    imgs, vals = dataset.__getDataAlongFactor__(f)
    for col, (img, val) in enumerate(zip(imgs, vals)):
        axs[row, col].imshow(img)
        axs[row, col].set_title(val)

[a.axis("off") for a in axs.ravel()]
fig.subplots_adjust(wspace=.05, hspace=.1)
plt.show()
```

**Comment by bordesf** [comment]
Hi @ThaddaeusWiedemer, thank you for raising this issue. So for context, the way those images were sampled was by first selecting a background, then going through all characters and factors of variations for this specific background. Then we switched to the next background and so on. It appears that the first character that is loaded just after switching background is the goldfish one. So if the background is not fully charged, those artifact would be especially seen on the goldfish character. 

This should not impact any other character than the goldfish. I am gonna take some times in the next days/weeks to investigate this further and to sample the goldfish images again.

**Comment by bordesf** [comment]
Hi @ThaddaeusWiedemer, so I verified all the classes and as expected this issue concerns only the Goldfish class. Mostly because this was always the first character to load when changing environment. The bad renders of goldfish are limited to around 192 images, which is less than 0.1% of the dataset content (which contain 200K images), so this should not have any statistical incidence for downstream evaluations nor training.

I will add a warning on the README concerning PUG: Animals and this specific issue.

**Comment by ThaddaeusWiedemer** [comment]
Awesome! Thank you so much for looking into this, @bordesf, and outlining the extent of the issue!
